### ISSUE TITLE
Integration with Relay

### ISSUE THREAD

**Issue by sedubois** [graphcool-examples/auth0-lock-example#3]
Thanks for the example 😊 I'm trying to adapt to Relay. I got the first part of getting the token from auth0, and now take inspiration from the [instagram create post example](https://github.com/graphcool-examples/react-relay-instagram-example/blob/master/src/components/CreatePage.js#L48): 

https://github.com/sedubois/belong/compare/gql...gql-auth

But I get `Uncaught Error: RelayMutationQuery: Invalid field name on fat query, `viewer``. Would you know what I'm missing?

**Comment by schickling** [comment]
So one error I'm spotting is that you're using the `createUser` mutation but expecting the `SigninPayload` instead of the `CreateUserPayload`. Could that be the problem?

**Comment by sedubois** [comment]
@schickling I used that because it's documented that way in GraphiQL: `createUser(input: SignupUserInput!): SigninPayload!`. I don't see `CreateUserPayload`. Do you have API docs somewhere?

**Comment by sorenbs** [comment]
Hi @sedubois 

Thanks for reporting this. It appears that we have two bugs in the relay api. I will update this when fixed.

- [ ] The payload of the `createUser` mutation has the wrong name
- [ ] There should be a viewer field in the payload

**Comment by sorenbs** [comment]
These two changes are rolling out over the next 45 minutes. Please reopen this issue if you still have trouble integrating with Relay :-)

**Comment by sedubois** [comment]
@sorenbs Thanks! I checked with the Playground and indeed now `createUser` takes a `CreateUserPayload!`. I also double-checked I'm still able to create a user through the playground.

Therefore I changed my code (see [here](https://github.com/sedubois/belong/commit/c51a590a64131236c1bc298c2f091becc4a2c072)) to 
```
getFatQuery() {
  return Relay.QL`fragment on CreateUserPayload {user}`;
}
```

However, I still see the same symptom. Am I missing something else?
(NB: I cannot reopen issue myself)

**Comment by sorenbs** [comment]
Have you tried adding viewer to the fat query?

**Comment by sedubois** [comment]
Oh yes! That works. Relay mutations are still mysterious to me. Thanks @sorenbs 😊

**Comment by sorenbs** [comment]
Excellent :-D
